"""Pydantic schemas for the recommendation (learning-roadmap) flow.

The flow has three request/response shapes:

* ``SkillAnalysis`` - Team 1's skill-analysis JSON, received in the request body
  of the *generate* endpoint. It is used only to build the roadmap and is never
  persisted.
* ``RoadmapPlan`` (and its nested ``WeekPlan`` / ``RoadmapCourseRef``) - the
  week-by-week plan produced by Gemini and stored as a JSONB document.
* ``RoadmapResponse`` - the persisted roadmap returned by the generate and fetch
  endpoints.
"""

from datetime import datetime
from typing import Annotated, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SkillGap(BaseModel):
    """A single skill the employee needs to improve, with its target level."""

    model_config = ConfigDict(populate_by_name=True)

    skill: str
    required_level: Annotated[int, Field(alias="requiredLevel")]


class SkillAnalysis(BaseModel):
    """Team 1's skill-analysis payload, passed in the request body of the
    generate endpoint. Only ``skill_gaps``, roles and ``skills`` drive roadmap
    generation; the remaining fields are accepted for completeness but ignored.

    Aliases are declared via ``Annotated[..., Field(alias=...)]`` (rather than as
    an assignment default) so they survive the way FastAPI re-wraps the top-level
    request-body model, which otherwise triggers Pydantic's
    ``UnsupportedFieldAttributeWarning``.
    """

    model_config = ConfigDict(populate_by_name=True)

    skill_id: Annotated[Optional[UUID], Field(alias="skillId")] = None
    user_id: Annotated[UUID, Field(alias="userId")]
    username: Optional[str] = None
    email: Optional[str] = None
    current_role: Annotated[Optional[str], Field(alias="currentRole")] = None
    target_role: Annotated[Optional[str], Field(alias="targetRole")] = None
    skills: Annotated[Dict[str, int], Field(default_factory=dict)]
    skill_gaps: Annotated[List[SkillGap], Field(default_factory=list, alias="skillGaps")]
    role_alignment: Annotated[Optional[str], Field(alias="roleAlignment")] = None
    resume_path: Annotated[Optional[str], Field(alias="resumePath")] = None
    status: Optional[str] = None
    created_at: Annotated[Optional[datetime], Field(alias="createdAt")] = None


class RoadmapCourseRef(BaseModel):
    """A course referenced inside a week of the roadmap. Mirrors the relevant
    subset of the ``courses`` table row selected via vector search."""

    course_id: UUID
    course_name: str
    provider: Optional[str] = None
    url: Optional[str] = None
    duration_hours: Optional[float] = None
    skills_taught: List[str] = Field(default_factory=list)


class WeekPlan(BaseModel):
    """One week of the learning roadmap."""

    week: int
    focus: str
    skills: List[str] = Field(default_factory=list)
    courses: List[RoadmapCourseRef] = Field(default_factory=list)
    activities: List[str] = Field(default_factory=list)


class RoadmapPlan(BaseModel):
    """The full week-by-week learning plan generated by Gemini."""

    summary: str
    total_weeks: int
    weeks: List[WeekPlan] = Field(default_factory=list)


class RoadmapResponse(BaseModel):
    """A persisted roadmap, returned by the save and fetch endpoints."""

    roadmap_id: UUID
    user_id: UUID
    target_role: Optional[str] = None
    status: str
    plan: RoadmapPlan
    created_at: Optional[datetime] = None
